---
- name: Install and configure Velociraptor
  hosts: all
  become: yes
  tasks:
    - name: Ensure system is up-to-date
      apt:
        update_cache: yes
        upgrade: dist

    - name: Download Velociraptor
      get_url:
        url: https://github.com/Velocidex/velociraptor/releases/download/v0.72/velociraptor-v0.72.3-linux-amd64
        dest: /usr/local/bin/velociraptor
        mode: '0755'

    - name: Create Velociraptor configuration directory
      file:
        path: /etc/velociraptor
        state: directory
        mode: '0755'

    - name: Copy Velociraptor configuration file
      copy:
        src: velociraptor.config.yaml
        dest: /etc/velociraptor/velociraptor.config.yaml
        mode: '0644'

    - name: Write Velociraptor systemd service file
      copy:
        dest: /etc/systemd/system/velociraptor.service
        content: |
          [Unit]
          Description=Velociraptor Server
          After=network.target

          [Service]
          ExecStart=/usr/local/bin/velociraptor --config /etc/velociraptor/velociraptor.config.yaml frontend
          Restart=always
          User=root

          [Install]
          WantedBy=multi-user.target

    - name: Reload systemd to apply new service
      command: systemctl daemon-reload

    - name: Enable and start Velociraptor service
      systemd:
        name: velociraptor
        enabled: yes
        state: started

    - name: Allow Velociraptor ports through the firewall
      ufw:
        rule: allow
        port: '8000'
        proto: tcp

    - name: Allow Velociraptor client port through the firewall
      ufw:
        rule: allow
        port: '8001'
        proto: tcp
